base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.routes),
    path('usuarios/', views.usuarios),
    path('amigos/<str:usuario>', views.amigos),
    path('posts/<str:usuario>', views.posts),
    path('seguir/<str:usuario1>/<str:usuario2>', views.seguir),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.registerPage),
    path('login/', views.loginPage),
    path('logout/',views.logoutPage),

    path('', views.home),

    path('perfil/', views.perfilPage),
    path('publicar/', views.publicacion),
    path('comment/', views.comentar),
    path('megusta/', views.megusta),

    path('amigos/', views.amigos),
    path('seguir/', views.seguir),
    path('eliminar/', views.eliminar),

    path('soporte/', views.soportePage),
]

cheep/urls.py
# RUTA RAIZ
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    
    # def __str__(self):
    #     return self.title
    
class Comment(models.Model):
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

class Amigos(models.Model):
    user = models.ForeignKey(User, related_name='amigos', on_delete=models.CASCADE)
    follow= models.ForeignKey(User,related_name='amigo_de', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['user', 'follow']

class Soporte(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()

class Megusta(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

base/api/views.py
from django.http import JsonResponse
from ..models import Post, Megusta, Comment, Amigos, Soporte
from django.contrib.auth.models import User

def routes(request):
    routes =[
        'GET /api/usuarios',
        'GET /api/amigos/<str:usuario>',
        'GET /api/posts/<str:usuario>',
        'GET /api/seguir/<str:usuario1>/<str:usuario2>',
    ]
    return JsonResponse(routes, safe=False)

def usuarios(request):
    usuarios= User.objects.all()
    data = []
    for usuario in usuarios:
        data.append({
            'username': usuario.username,
            'first_name': usuario.first_name,
            'last_name' : usuario.last_name,
            'email': usuario.email
        })

    return JsonResponse(data, safe=False)

def amigos(request, usuario):
    data=[]
    id = User.objects.get(username=usuario)
    amigos = Amigos.objects.filter(user=id)
    for amigo in amigos:
        data.append({
            'username': amigo.follow.username,
            'first_name': amigo.follow.first_name,
            'last_name' : amigo.follow.last_name,
        })
    return JsonResponse(data, safe=False)

def posts(request, usuario):
    data=[]
    id = User.objects.get(username=usuario)
    posts = Post.objects.filter(user=id)
    for post in posts:
        comentariosData = []
        comentarios = Comment.objects.filter(post=post)
        for comentario in comentarios:
            comentariosData.append({
                'username': comentario.user.username,
                'text': comentario.text
            })
        megustasData =[]
        megustas = Megusta.objects.filter(post=post)
        for megusta in megustas:
            megustasData.append({
                'username': megusta.user.username,
            })
        data.append({
            'username' : id.username,
            'text': post.text,
            'comentarios': comentariosData,
            'megustas': megustasData
        })
    return JsonResponse(data, safe=False)


def seguir(request, usuario1, usuario2):
    usuario = User.objects.get(username=usuario1)
    follow = User.objects.get(username=usuario2)
    try:
        comprobar= Amigos.objects.get(user=usuario, follow=follow)
        data = {'message': f'{usuario1} ya sigue a {usuario2}'}
    except:
        amigo = Amigos(user=usuario, follow=follow)
        amigo.save()
        data = {'message': f'{usuario1} acaba de convertirse en michiamigo de {usuario2}'}
    return JsonResponse(data, safe=False)

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Post, Comment, Amigos, Soporte, Megusta
from django.db.models import Q
from functools import reduce

# Create your views here.

def registerPage(request):
    if (request.method == 'POST'):
        username = request.POST.get('username')
        email= request.POST.get('email')
        name= request.POST.get('firs_name')
        last_name= request.POST.get('last_name')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        if (password != confirm_password):
            messages.error(request, 'Las contraseñas no coinciden')
            return redirect('/registro')
        User.objects.create_user(username, email =email, first_name=name, last_name=last_name, password=password)
        return redirect('/login')
    return render(request,'registerPage.html')

            
def soportePage(request):
    if (request.method == 'POST'):
        email = request.POST.get('email')
        sugerencia = request.POST.get('sugerencia')
        Soporte.objects.create(text = sugerencia, email = email)
        messages.success(request, 'Se envio la sugerencia')

    return render (request,'soporte.html')

def loginPage(request):
    if (request.method == 'POST'):
        username= request.POST.get('username')
        password= request.POST.get('password')
        if User.objects.filter(username=username).exists():
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Se inició sesión correctamente')
                return redirect('/')
        messages.success(request, 'Datos incorrectos')
    

    return render(request,'login.html')

def logoutPage(request):
    logout(request)
    return redirect ('/login/')

def home(request):
    if str(request.user) == 'AnonymousUser':
        return redirect('/login/')
    follows = Amigos.objects.filter(user= request.user)
    
    # listaFollows =[]
    # for follow in follows:
    #     listaFollows.append(Q(user=follow.follow))
    #     print(follow.follow)
    listaFollows= [Q(user=follow.follow) for follow in follows]

    filtro=[Q(user=request.user)]+ listaFollows
    filtroT= reduce(lambda x, y:x | y, filtro)
    publicaciones = Post.objects.filter(filtroT).order_by('-created')
    data={
        'posts': publicaciones,

    }
    # id_admin = User.objects.get(username='admin')
    # posts= Post.objects.filter(Q(user=request.user)|Q(user=id_admin.id)).order_by('-created')
    return render (request,'home.html', data)

def perfilPage(request):
    if str(request.user) == 'AnonymousUser':
        return redirect('/login/')
    usuario = User.objects.get(username=request.user)
    posts= Post.objects.filter(user=request.user).order_by('-created')
    if len(posts) == 0: posts = None
    data = {'usuario':usuario, 'posts': posts}   
    return render (request,'perfil.html', data)

def publicacion(request):
    id = request.POST.get('id')
    text = request.POST.get('text')
    if(id is None and text !=''):
        Post.objects.create(text = text,user = request.user)
        messages.success(request, 'Post creado correctamente')
    return redirect('/')

def comentar(request):
    p = Post.objects.get(id = request.POST.get('post'))
    Comment.objects.create(
        text = request.POST.get('text'),
        user = request.user,
        post = p
    )
    return redirect('/')

def amigos(request):
    usuarios = User.objects.all()
    agregados = Amigos.objects.filter(user=request.user)
    usuario = User.objects.get(username=request.user)
    sugerencias= []
    for i in usuarios:
        coincide= False
        for e in agregados:
            if i == e.follow:
                coincide = True 
                break

        if not coincide:
            sugerencias.append(i)

    data ={
        'usuarios':usuarios,
        'usuario' : usuario,
        'agregados': agregados,
        'sugerencias': sugerencias
    }
    
    return render (request,'amigos.html', data)

def megusta(request):
    usuario = User.objects.get(username=request.user)
    pId = request.POST.get('megusta')
    post = Post.objects.get(id=pId)
    try:
        comprobar = Megusta.objects.get(user= usuario, post= post)
        comprobar.delete()
    except:
        Megusta.objects.create(user = request.user,post = post)
    return redirect('/')

def seguir(request):
    follow = request.POST.get('amigo')
    usuario = User.objects.get(username=request.user)
    follow = User.objects.get(username=follow)
    try:
        comprobar= Amigos.objects.get(user=usuario, follow=follow)
    except:
        amigo = Amigos(user=usuario, follow=follow)
        amigo.save()
   

    return redirect('/amigos/')

def eliminar(request):
    follow = request.POST.get('amigo')
    usuario = User.objects.get(username=request.user)
    follow = User.objects.get(username=follow)
    amistad= Amigos.objects.get(user=usuario, follow=follow)
    amistad.delete()

    return redirect('/amigos/')

base/templates/amigos.html
{% extends "layouts/main.html" %}
{% load static %}


{% block content %}
<h1>Mis michis de corazón</h1>
<br/>
{% for a in agregados %}
    <div class="card p-3 row bg-dark text-light" style="width: 650px; height: 80px;">
       <div class="row col-12">
        <div class="col-4">
            <img src="{% static 'img/amigos.jpg' %}" alt="mi imagen" style="border-radius: 50%; width: 100px; height: 80px;">
        </div>
        <div class="col-4">
                <h2>{{a.follow}}</h2>
            </div>
        <div class="col-4">
            <form method="POST" action="/eliminar/">
                {% csrf_token %}
                <input type="hidden" value="{{a.follow}}" name="amigo">
                <button class="btn btn-danger" type="submit">Desterrar michi</button>
            </form>
        </div>
       </div>
    </div>
    <br/>
{% endfor %}
<br/>
<h1>Michis huerfanos</h1>
{% for u in sugerencias %}
{% if u != usuario %}

<div class="card p-3 row bg-dark text-light" style="width: 650px; height: 80px;">
       <div class="row col-12">
        <div class="col-4">
            <img src="{% static 'img/enemigos.jpg' %}" alt="mi imagen" style="border-radius: 50%; width: 100px; height: 80px;">
        </div>
        <div class="col-4">
                <h2>{{u}}</h2>
            </div>
        <div class="col-4">
            <form method="POST" action="/seguir/">
                {% csrf_token %}
                <input type="hidden" value="{{u}}" name="amigo">
                <button class="btn btn-primary" type="submit">Adoptar michi</button>
            </form>
        </div>
       </div>
    </div>
    <br/>


    {% endif %}
{% endfor %}
{% endblock %}

base/templates/home.html
{% extends "layouts/main.html" %}


{% block content %}
<!-- <h1>Inicio</h1> -->
{% load static %}

<form method="POST" action="/publicar/">
    {% csrf_token %}
    <!-- {% if post is not None %}
        <input type="number" value="{{post.id}}" name="id">
    {% endif %} -->

    <div class="form-group my-3">
        <label>¿Qué estás pensando?</label>
        <textarea class="form-control" name="text">{% if post is not None %}{{post.text}}{% endif %}</textarea>
        
    </div>

    <button class="btn btn-primary" type="submit">Publicar</button>
</form>
<br/>
{% if posts == None %}

<h1>No hay publicaciones</h1>

{% endif %}

<label><b>Solo puedes ver tus publicaciones y las de tus michis de corazón</b> 😸</label>
<br/>
<br/>
{% for p in posts %}
<div class="card p-3 row bg-dark text-light">

    <div class="col-12 row">
        <img src="{% static 'img/icono.png' %}" alt="mi imagen" style="border-radius: 50%; width: 100px; height: 80px;">
        <h1 class="col-4"><b>{{p.user}}</b></h1>
        <p class="col-4">{{p.created}}</p>
    </div>
    <br/>
    <h3>{{p.text}}</h3>
    <div class="row">
        <div class="col-1">
            <form method="POST" action="/megusta/">
                {% csrf_token %}
                <input type="hidden" value="{{p.id}}" name="megusta">
                <button class="btn btn-primary" type="submit">❤️</button>
                
            </form>
        </div>
       <div class="col-11">
            <span><b>Le gusta a:</b> </span>
            {% for m in p.megusta_set.all %}
            <span>{{m.user}} </span>
            {% endfor %}
       </div>
   </div>
   <br/>

    <div class=" px-5">
        <div class="px-5">
            {% if request.user.is_authenticated %}
            <form method="POST" action="/comment/">
                {% csrf_token %}
                <input type="hidden" value="{{p.id}}" name="post">
                <div class="form-group my-3">
                    <label>Comentar</label>
                    <textarea class="form-control" name="text" placeholder="Escribe un comentario"></textarea>
                </div>
                
                <button class="btn btn-primary" type="submit">Enviar comentario</button>
            </form>
        {% endif %}
        </div>
    </div>
    <br/>
    <h5>Comentarios:</h5>
    {% for c in p.comment_set.all %}
        <div class="p-3">
            <div class="card px-3">
                <p><b>{{c.user}}</b>: {{ c.text }}</p>
                <p>{{c.created}} </p>
            </div>
        </div>
        {% endfor %}
    
</div>
<br/>
{% endfor %}


{% endblock %}

base/templates/login.html
{% extends "layouts/main.html" %}

{% block content %}

<h1>Iniciar Sesión</h1>
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group my-3">
        <label>Usuario</label>
        <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
        
    </div>
    <div class="form-group my-3">
        <label>Contraseña</label>
        <input type="password" class="form-control" name="password" placeholder="Contraseña">
    </div>
    <div>

        <a href="/registro">Aún no tengo cuenta</a>
    </div>
    <button class="btn btn-primary" type="submit">Iniciar Sesión</button>
</form>
{% endblock %}

base/templates/perfil.html
{% extends "layouts/main.html" %}
{% load static %}

{% block content %}
<h1>Mi michiperfil</h1>
<br/>
<br/>
<div class="row">
    <div class="col-4">

        <img src="{% static 'img/perfil.png' %}" alt="mi imagen" style="border-radius: 50%; width: 150px; height: 120px;">
    </div>
    <div class="col-8">
        <h1>{{usuario.username}}</h1>
        <p>{{usuario.first_name}} {{usuario.last_name}}</p>
    </div>
</div>


<form method="POST" action="/publicar/">
    {% csrf_token %}
    <!-- {% if post is not None %}
        <input type="number" value="{{post.id}}" name="id">
    {% endif %} -->

    <div class="form-group my-3">
        <label>Publicación</label>
        <textarea class="form-control" name="text">{% if post is not None %}{{post.text}}{% endif %}</textarea>
        
    </div>

    <button class="btn btn-primary" type="submit">Publicar</button>
</form>
<br/>
{% if posts == None %}

<h1>No hay publicaciones</h1>

{% endif %}


{% for p in posts %}
<div class="card p-3 row bg-dark text-light">

    <div class="col-12 row">
        <img src="{% static 'img/icono.png' %}" alt="mi imagen" style="border-radius: 50%; width: 100px; height: 80px;">
        <h1 class="col-4"><b>{{p.user}}</b></h1>
        <p class="col-4">{{p.created}}</p>
    </div>
    <br/>
    <h3>{{p.text}}</h3>
    <div class="row">
        <div class="col-1">
            <form method="POST" action="/megusta/">
                {% csrf_token %}
                <input type="hidden" value="{{p.id}}" name="megusta">
                <button class="btn btn-primary" type="submit">❤️</button>
                
            </form>
        </div>
       <div class="col-11">
            <span><b>Le gusta a:</b> </span>
            {% for m in p.megusta_set.all %}
            <span>{{m.user}} </span>
            {% endfor %}
       </div>
   </div>
   <br/>

    <div class=" px-5">
        <div class="px-5">
            {% if request.user.is_authenticated %}
            <form method="POST" action="/comment/">
                {% csrf_token %}
                <input type="hidden" value="{{p.id}}" name="post">
                <div class="form-group my-3">
                    <label>Comentar</label>
                    <textarea class="form-control" name="text" placeholder="Escribe un comentario"></textarea>
                </div>
                
                <button class="btn btn-primary" type="submit">Enviar comentario</button>
            </form>
        {% endif %}
        </div>
    </div>
    <br/>
    <h5>Comentarios:</h5>
    {% for c in p.comment_set.all %}
        <div class="p-3">
            <div class="card px-3">
                <p><b>{{c.user}}</b>: {{ c.text }}</p>
                <p>{{c.created}} </p>
            </div>
        </div>
        {% endfor %}
    
</div>
<br/>
{% endfor %}



{% endblock %}

base/templates/registerPage.html
{% extends "layouts/main.html" %}

{% block content %}

<h1>Iniciar Sesión</h1>
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group my-3">
        <label>Usuario</label>
        <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
    </div>

    <div class="form-group my-3">
        <label>email</label>
        <input type="email" class="form-control" name="email" placeholder="Email">
    </div>

    <div class="form-group my-3">
        <label>Nombre</label>
        <input type="text" class="form-control" name="firs_name" placeholder="Nombre">
    </div>

    <div class="form-group my-3">
        <label>Apellido</label>
        <input type="text" class="form-control" name="last_name" placeholder="Apellido">
    </div>

    <div class="form-group my-3">
        <label>Contraseña</label>
        <input type="password" class="form-control" name="password" placeholder="Contraseña">
    </div>

    <div class="form-group my-3">
        <label>Confirmar contraseña</label>
        <input type="password" class="form-control" name="confirm_password" placeholder="Confirmar contraseña">
    </div>
    <button class="btn btn-primary" type="submit">Registro</button>
</form>
{% endblock %}

base/templates/soporte.html
{% extends "layouts/main.html" %}
{% load static %}

{% block content %}

<h1>Michisoporte</h1>
<br/>
<label><b>Envíanos un mensaje y uno de nuestros michioperadores se pondrá en contacto contigo</b> 😸</label>
<br/>
<br/>
<div class="card p-3 row bg-dark text-light">
    <div class="row col-12">
        <div class="col-5">
            <img src="{% static 'img/soporte.jpg' %}" alt="mi imagen" style="border-radius: 50%; width: 250px; height: 200px;">
        </div>
        <div class="col-7">
            <form method="POST" action="">
                {% csrf_token %}
        
                <div class="form-group my-3">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" placeholder="Email">
                </div>
        
                <div class="form-group my-3">
                    <label>Sugerencia</label>
                    <input type="text" class="form-control" name="sugerencia" placeholder="sugerencia">
                </div>
                <button class="btn btn-primary" type="submit">Enviar</button>
            </form>
        </div>
    </div>
    
</div>

{% endblock %}